# docker-compose up
# psql -h localhost -U postgres
version: "3"
services:
  postgresql:
    image: postgres:12.3
    container_name: "TestContainerPostgreSqlDemoApplicationDB"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - ../src/main/resources/db/docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql